### PR TITLE
Update to AVA v6

### PR DESCRIPTION
**Pull request by razor-x**
Based on https://github.com/seamapi/fake-template/pull/50

I cannot figure out what is the issue with the test failure. However I have seen this before trying to update this to AVA v6 (still stuck on v5): https://github.com/seamapi/javascript-http

### CODE REVIEW

**Comment by razor-x** [comment]
@codetheweb Just want to see if you have any ideas here given how much you have worked with AVA. This is the first time I've reproduced the same error in two repos, so maybe we can learn something new: https://github.com/seamapi/javascript-http/pull/65

**Comment by codetheweb** [comment]
Does seamapi/javascript-http use shared workers? I remember seeing this error before in edgespec, but I thought it was my fault at the time.

**Comment by razor-x** [comment]
It starts and uses the fake, but I'm not sure if that means it uses shared workers or not.

**Comment by codetheweb** [comment]
I think it's an internal AVA bug with `t.throwsAsync()`? I think? Pretty sure it's a result of the Axios error not serializing properly.

e.g. when run outside `t.throwsAsync()` it works fine, and if you try/catch `t.throwsAsync()` you can see the internal AVA error

Screenshot 2024-03-21 at 17 11 49

Screenshot 2024-03-21 at 17 12 34

**Pull request closed without merging**
